#!/bin/sh


line=`grep "__version__" html2rest.py | sed "s/__version__ = //g"`
stripped_line=`echo $line |sed "s/dev//g"`

if [ $line = $stripped_line ]; then
    # not dev
    python setup.py sdist --formats=gztar,zip register upload
else
    # dev
    python setup.py sdist --formats=gztar,zip
fi

